# Site settings
title: おもしぇてっく
description: >
  スタートアップの経営者とエンジニアに役立ちそうなことを記事にしています。
  このブログをきっかけに一緒に働きたいという経営者やエンジニアが見つかるといいなと思います。
url: https://omoshetech.com

# Conversion
markdown: kramdown

# Outputting
permalink: /:title/

# Markdown Processors
kramdown:
  auto_ids: false
